[book]
authors = ["Alex Fan"]
language = "zh_CN"
multilingual = true
src = "src"
title = "Road to Gentoo on RISC-V"

[build]
build-dir = "docs"


[output.html]
mathjax-support = true

[output.html.playground]
editable = true
line-numbers = true
